#!/usr/bin/env python2.7

import rospy
import os.path
import yaml  # pip install PyYAML==5.1.2

from geometry_msgs.msg import PoseWithCovarianceStamped
from location_recorder.srv import RoomPose
from location_recorder.srv import RoomPoseResponse


def callback_srv(req):
    """Writes robot's current pose and room location to the room_record.yaml file

    Return
    ----------
    Server response confirming file save
    """
    # prepare new entry
    global pose
    pos = pose.pose.position
    ori = pose.pose.orientation
    output = {
        req.room_label: {
            "position": [
                "x:{0}".format(pos.x),
                "y:{0}".format(pos.y),
                "z:{0}".format(pos.z)],
            "orientation": [
                "x:{0}".format(ori.x),
                "y:{0}".format(ori.y),
                "z:{0}".format(ori.z)]
        }
    }
    # see if file already exists - if so, read it in first
    if os.path.exists('./src/location_recorder/records/room_record.yaml'):
        with open(r'./src/location_recorder/records/room_record.yaml', 'r') as file:
            data = yaml.full_load(file)
            data = dict(data)
            data.update(output)
            output = data
    # write to the yaml ile
    with open(r'./src/location_recorder/records/room_record.yaml', 'w') as file:
        yaml.dump(output, file, default_flow_style=False, sort_keys=False)
    # return success message
    return RoomPoseResponse("Entry saved in file")  # send the response to the client


def callback_pose(msg):
    """Gets the robot pose from amcl_pose topic and updates pose global var
    """
    global pose
    pose = msg.pose


def room_location_server():
    """Continuously updates robot pose and checks for server requests
    """
    rospy.init_node("room_location_server")
    rospy.Subscriber("amcl_pose", PoseWithCovarianceStamped, callback_pose)
    rospy.Service("room_service", RoomPose, callback_srv)
    rospy.loginfo("I am waiting for requests...")
    rospy.spin()


if __name__ == "__main__":
    pose = None
    room_location_server()
